<option value=""></option>
<optgroup label="Education">
<option value="Certificate">Certificate Ⅰ-Ⅳ</option>
<option value="Diploma">Diploma</option>
<option value="Bachelor">Bachelor</option>
<option value="Master">Master</option>
<option value="Phd">Phd/Research</option>
<option value="GeneralEng">General English</option>
<option value="IELTS">IELTS</option>
<option value="Cambridge">Cambridge</option>
<option value="TESOL">TESOL</option>
<option value="PYP">PYP (Professional Year Program)</option>
<option value="NAATI">NAATI</option>
<option value="OtherC">Other Course</option>
<optgroup label="Migration">
<option value="Student">Student Visa</option>
<option value="485 Visa">485 Visa</option>
<option value="457 Visa">457 (Sponsor) Visa</option>
<option value="189 Visa">189 (P.R) Visa</option>
<option value="Partner Visa">Partner Visa</option>
<option value="Other Visa">Other Visa</option>